# Staticman konfiguracija
comments:
  allowedFields: ["name", "points", "min", "sec", "date"]
  branch: "main"  # Branch, kamor bodo shranjeni novi komentarji
  commitMessage: "rekord"
  filename: "records.json"
  format: "json"
  moderation: false  # Nastavi na "false", če želiš samodejno objavo brez moderacije
  path: ""  # Pot, kamor se shranjujejo podatki v repozitoriju
  #requiredFields: ["name", "message"]  # Polja, ki morajo biti obvezno izpolnjena
  transforms:
    content: "md"

# Javni ključ za šifriranje podatkov
publicKey: "AAAAB3NzaC1yc2EAAAADAQABAAABAQCjcj0ELL1FgDqPz7EuRi1V00i5o42XqcrOtXEs3QME3rwMIZrHr6Wa/fJ++vE0v0xAOOK/XoSAaZaDBEnp9zIuu5PiB3Wly3WI6QWEjLpth4PKGU9sO29t2bsgH6aBSPd52thVKjZUO5hd5bgGiQVN5QcvPLxWR2Cd0QWVCLnEVbEdU4ZgQ3/xi/cUsgMzuMdt+qJaCi1B8LnvxGTe0sPUTjHzc5xO1SMmnF18T28fYsP+MQOozd98sXI3FYt93bwVKSOb4lpdfk5zAHsREw9BbzhgMQ1ps8UDQzismPnelKCVudf+WUJFMHezyfKZZfH0cSxLDxa9JMolPnJH2c6B"
